feat: Allow specifying additional TGW routes in attached VPCs
terraform-aws-modules/terraform-aws-transit-gateway pull request #132
Opened 2024-07-17 00:44 UTC by partcyborg

## Description
Adds parameter `tgw_additional_vpc_cidrs` to the `vpc_attachments` map that enables adding additional `aws_route` resources that send traffic across the TGW VPC attachment.

Changes the name of the existing `aws_route` resource from `this` since there are now more than one in the state file.

## Motivation and Context
In our environment we have two CIDR blocks that need to transit from the VPC across the TGW network: `10.0.0.0/8` and `172.16.0.0/12`. Unfortunately this is not possible to do with the module as it is today.

With this change we can add `aws_route` entries for both CIDR blocks to our VPC route tables.

## Breaking Changes
This change increments the minimum required terraform version to 1.1 in order to take advantage of `moved` blocks.

In order to implement this I had to add a second `aws_route` resource because the existing one is keyed only on route table ID which is no longer a unique value for route resources.

Commonly accepted Terraform style rules indicate that `this` is only an acceptable resource name if it is the only one of its type in a module. Since there are now two `aws_route` resources, I changed the name of the existing `this` resource to `destination_cidr` so that this style rule is still valid.

While I personally feel that the overwhelming majority of module users should already be using a version equal to or greater than Terraform 1.1, if bumping this requirement is undesirable I would fine with reverting the resource rename and leaving the minimum required version as is.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2024-07-17 00:46 UTC, partcyborg commented
NOTE: this change has the same bootstrapping problem as #111, but it works correctly when the VPC resources are configured ahead of time (or in a separate state file as we do in our terraform)

2024-07-24 19:58 UTC, elopsod commented
Hi @antonbabenko coul you please take a look
Thank you!

2024-09-13 05:29 UTC, elkh510 commented
Hi @antonbabenko could you please take a look
Thank you!

2024-10-14 06:56 UTC, elkh510 commented
Hi
Still actually

2024-11-15 05:34 UTC, elkh510 commented
Hi
Still actually

2024-12-13 22:49 UTC, partcyborg commented
pinging this again. @antonbabenko were you able to look at this? Or @elkh510 is there someone else that can?

2025-01-13 05:57 UTC, elopsod commented
Hi
Still actually

2025-02-13 04:39 UTC, elopsod commented
Hi
Still actually

2025-04-10 03:31 UTC, elopsod commented
Hi
Still actually

2025-05-11 04:46 UTC, elkh510 commented
Hi
Still actually

2025-06-12 03:31 UTC, elkh510 commented
Hi
Still actually

2025-06-19 07:09 UTC, pongsakfreshket commented
Hi Please verify and merge please

2025-06-19 07:09 UTC, pongsakfreshket approved these changes

2025-07-20 03:42 UTC, elkh510 commented
Hi
Still actually

2025-07-25 22:44 UTC, partcyborg commented
> Hi Please verify and merge please

Hey @pongsakfreshket i need an approval from someone authorized on this project. Unfortunately it looks like your approval doesn't count here as I still can't merge.

2025-08-23 19:35 UTC, elkh510 commented
Hi
Still actually

2025-09-23 03:51 UTC, elkh510 commented
Hi
Still actually

2025-10-16 00:04 UTC, partcyborg commented
Hello @antonbabenko I have re-based this PR to match the recent changes

2025-10-24 08:53 UTC, yyarmoshyk requested changes
@antonbabenko I think this is very important change.

@partcyborg please check my comments.

2025-10-24 22:26 UTC, partcyborg commented on main.tf
> +moved {
As stated above, your suggestion will cause an outage for all users of this module. I really don't think this is the right approach here.

2025-11-10 12:14 UTC, Peneheals commented
As far as I understand the current situation, the PR works (and if not, @partcyborg and/or @yyarmoshyk are happy to improve it or align it with the needs!). It has been tested multiple times, but we’re still blocked because we can’t decide which direction to take:

1. Remain backward compatible and
    1. keep using the “old” `aws_route.this resource` without modifications, but violate Terraform styling principles, or
    1. keep the PR as is, without touching the “old” resources, and remain Terraform-style compliant, or
1. introduce a breaking change that destroys and rebuilds all the “old” resources: update the code and remove the `moved` block (as a different approach).

@antonbabenko @bryantbiggs Could you please share your opinion on this matter, which was discussed specifically [here](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/pull/132#discussion_r2459393887)
?

I saw that you have limited (or no) time to code, but I hope you have time to make the above decision and review this important question, so the guys can move forward and finalize the PR.

2025-11-10 13:12 UTC, bryantbiggs commented
if we are going to make a breaking change, we should make it once and get to the current desired state (i.e. - #113)

we should not make many, sequential, smaller breaking changes

2025-12-06 01:32 UTC, partcyborg commented
> if we are going to make a breaking change, we should make it once and get to the current desired state (i.e. - #113)
> 
> we should not make many, sequential, smaller breaking changes

@bryantbiggs neither of the implementation options i provided are "breaking" changes, including the one implemented in this PR. Upgrading to a new module version with this change will work without the destruction/creation of any resources.

I don't think breaking changes are EVER safe for a module like this, as in our use case this module under-pins critical HA network infrastructure. Furthermore, I don't think that it is a good idea to require users write their own `moved` block to account for the module change, as people are likely to not pin their module versions which would cause network outages for them if they get automatically upgraded

2025-12-16 15:59 UTC, bryantbiggs commented
> > if we are going to make a breaking change, we should make it once and get to the current desired state (i.e. - #113)
> > we should not make many, sequential, smaller breaking changes
> 
> @bryantbiggs neither of the implementation options i provided are "breaking" changes, including the one implemented in this PR. Upgrading to a new module version with this change will work without the destruction/creation of any resources.
> 
> I don't think breaking changes are EVER safe for a module like this, as in our use case this module under-pins critical HA network infrastructure. Furthermore, I don't think that it is a good idea to require users write their own `moved` block to account for the module change, as people are likely to not pin their module versions which would cause network outages for them if they get automatically upgraded

"breaking change" within Terraform is not so clear cut and dry - you are moving a resource named `this` to another name - which can have long term effects (when is it safe to use `this` again which is our norm, will it ever be safe to use again?). So that change alone is a blocker for me. I don't see the point in renaming the resource at this time

2026-01-16 01:23 UTC, partcyborg commented
> "breaking change" within Terraform is not so clear cut and dry - you are moving a resource named `this` to another name - which can have long term effects (when is it safe to use `this` again which is our norm, will it ever be safe to use again?). So that change alone is a blocker for me. I don't see the point in renaming the resource at this time

@bryantbiggs we would never have `aws_route.this` again as there are now two `aws_route` resources, and terraform naming convention states that `this` should only be used as a name if there is only one instance of the resource in the module.

If you are fine with violating this naming convention, then I am fine with removing the `moved` block.

I have updated the PR so we now have two `aws_route` resources
- `aws_route.this` - The route table entry for the default destination cidr block
- `aws_route.additional_cidrs` - The route table entries for any additional CIDR blocks provided though the `additional_cidrs` input


PTAL again.

2026-01-20 22:39 UTC, bryantbiggs commented
changing base - see thread here for more details https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/pull/113#issuecomment-3775166144

please fix conflicts and then the collective of folks can take a look

2026-01-22 01:54 UTC, partcyborg commented
> changing base - see thread here for more details [#113 (comment)](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/pull/113#issuecomment-3775166144)
> 
> please fix conflicts and then the collective of folks can take a look

@bryantbiggs i can't rebase this PR onto `develop/v4` as that feature branch has dropped the aws_route resources entirely. Is this expected? What is going on with this branch? Do you want me to completely re-implement route table support in the new branch?

2026-01-22 13:20 UTC, bryantbiggs commented
> > changing base - see thread here for more details [#113 (comment)](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/pull/113#issuecomment-3775166144)
> > please fix conflicts and then the collective of folks can take a look
> 
> @bryantbiggs i can't rebase this PR onto `develop/v4` as that feature branch has dropped the aws_route resources entirely. Is this expected? What is going on with this branch? Do you want me to completely re-implement route table support in the new branch?

I would like you to take a look at the `develop/v4` branch and see if your issue is resolved, or not. if it, please feel free to open an issue or PR to suggest changes. as I stated above through the link, this is an attempt to help move forward towards a solution that resolves a number of long outstanding PRs

There is already this https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/tree/develop/v4/modules/route-table which may resolve your original issue - but I will defer to you whether that is true or not

2026-03-05 00:45 UTC, closed without merging