TGW mutlicast support
terraform-aws-modules/terraform-aws-transit-gateway pull request #73
Opened 2022-05-04 12:49 UTC by alimakki

## Description
Add variable `enable_multicast_support` to configure TGW mutlicast enablement

## Motivation and Context
Current module does not accept parameter to enable multicast.

## Breaking Changes
None

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] Tested on a private staging environment on AWS

2022-05-05 13:00 UTC, antonbabenko requested changes
Looks good. Could you please update the minimum version of Terraform AWS provider in `versions.tf` to be 4.3.0? It will lead to a major release.

2022-05-05 13:31 UTC, alimakki commented
@antonbabenko thanks for the review!

I noticed that the AWS provider version in `versions.tf` is currently set to `>= 4.4` - would you like it changed to `>= 4.3.0` ? Also for the example modules?

2022-05-09 09:04 UTC, antonbabenko commented
@alimakki You are right. No need to touch `versions.tf`. I have fixed the docs, too.

2022-05-09 09:05 UTC, merged

2022-05-09 11:51 UTC, alimakki commented
thanks @antonbabenko !